spring:
  profiles:
    active: dev
#  jackson:
#    # 设置日期格式
#    date-format: yyyy-MM-dd HH:mm:ss
#    # 后台反参时，如果字段为null，则不返回该字段
#    default-property-inclusion: non_null
  servlet:
    multipart:
      max-file-size: 10MB # 限制单个上传文件的最大大小为10MB，如果上传的文件大小超过这个值，将会被拒绝上传
      max-request-size: 10MB # 限制整个上传请求的最大大小为10MB，这包括所有上传文件的大小之和。如果请求总大小超过这个值，将会被拒绝。

jwt:
  #签发者
  issuer: WL
  # 密钥
  secret: a74AnRpw/+4VYnliojdvJzegMTusYoJk9/MieLVWgNFhQU7qy+mkpPWXNagqmPc6sFuX6tdNS9ofO4v34ZsrdA==

  # TODO
  tokenExpireTime: 1440
  # token 请求头中的 key 值
  tokenHeaderKey: Authorization
  # token 请求头中的 value 值前缀
  tokenPrefix: Bearer