import fs from 'node:fs';
import path from 'node:path';

const root = new URL('.', import.meta.url).pathname;
const postsDir = path.join(root, 'posts');
const siteDir = path.join(root, 'site');
const posts = fs.readdirSync(postsDir).filter(f => f.endsWith('.md')).map(file => {
  const raw = fs.readFileSync(path.join(postsDir, file), 'utf8');
  const parts = raw.split(/^---\s*$/m);
  const fm = parts.length > 2 ? parts[1] : '';
  const body = parts.length > 2 ? parts.slice(2).join('---') : raw;
  const meta = {};
  fm.split('\n').forEach(line => { const i = line.indexOf(':'); if (i > 0) meta[line.slice(0, i).trim()] = line.slice(i + 1).trim(); });
  return { file, slug: file.replace(/\.md$/, ''), title: meta.title || file, date: meta.date || '', tags: (meta.tags || '').split(',').map(s => s.trim()).filter(Boolean), excerpt: meta.excerpt || '', draft: meta.draft === 'true', cover: meta.cover || '', content: body.trim() };
}).sort((a,b) => b.date.localeCompare(a.date));

fs.rmSync(siteDir, { recursive: true, force: true });
fs.mkdirSync(path.join(siteDir, 'posts'), { recursive: true });
const esc = s => String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const attr = s => esc(s).replaceAll("'",'&#39;');
function readingTime(md) { return Math.max(1, Math.ceil(md.replace(/[#>*`\-]/g,' ').trim().length / 350)); }
function slugify(s) { return s.toLowerCase().replace(/[^a-z0-9\u4e00-\u9fff]+/g,'-').replace(/^-|-$/g,''); }
function markdown(md) {
  const lines=md.split('\n');let html=[],toc=[],inCode=false,code=[],lang='';
  for(const raw of lines){
    if(raw.startsWith('```')){if(inCode){const src=esc(code.join('\n'));html.push(lang==='mermaid'?`<div class="mermaid">${src}</div>`:`<pre><code class="language-${esc(lang||'text')}">${src}</code></pre>`);code=[];lang='';inCode=false}else{inCode=true;lang=raw.slice(3).trim().toLowerCase()}continue}
    if(inCode){code.push(raw);continue}
    const line=esc(raw),m=line.match(/^(#{1,3})\s+(.+)$/);
    if(m){const level=m[1].length,text=m[2],id=slugify(text);if(level>=2)toc.push({level,text,id});html.push(`<h${level} id="${id}">${text}</h${level}>`);continue}
    if(line.startsWith('$$')&&line.endsWith('$$')&&line.length>4){html.push(`<div class="math-block">${line.slice(2,-2)}</div>`);continue}
    if(line.startsWith('> ')){html.push(`<blockquote>${line.slice(2)}</blockquote>`);continue}
    if(line.startsWith('- ')){if(!html.at(-1)?.startsWith('<ul>'))html.push('<ul>');html.push(`<li>${line.slice(2)}</li>`);continue}
    if(!line.trim()){if(html.at(-1)==='<ul>')html.push('</ul>');continue}
    html.push(`<p>${line.replace(/\*\*(.*?)\*\*/g,'<strong>$1</strong>').replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\[(.*?)\]\((.*?)\)/g,'<a href="$2">$1</a>')}</p>`);
  }
  if(inCode)html.push(`<pre><code class="language-${esc(lang||'text')}">${esc(code.join('\n'))}</code></pre>`);if(html.at(-1)==='<ul>')html.push('</ul>');return{html:html.join('\n'),toc};
}
const baseCss=fs.readFileSync(path.join(root,'style.css'),'utf8');
const enhancedCss=`.reading-progress{position:fixed;z-index:9999;left:0;top:0;width:100%;height:3px;background:var(--accent);transform-origin:left center;transform:scaleX(0)}.article-body img{max-width:100%;height:auto;border-radius:14px;cursor:zoom-in}.article-body .mermaid{margin:28px 0;padding:20px;border:1px solid var(--border);border-radius:14px;overflow:auto;background:var(--surface)}.math-block{overflow:auto;margin:24px 0;text-align:center}.katex-display{overflow:auto}.article-body pre{position:relative}.article-body pre code{background:transparent;padding:0}.copy-code{position:absolute;right:10px;top:10px;border:1px solid #555;background:#222;color:#eee;border-radius:7px;padding:5px 9px;cursor:pointer;font-size:12px}.related{margin-top:70px;border-top:1px solid var(--border);padding-top:32px}.related-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px}.related-card{border:1px solid var(--border);border-radius:14px;padding:20px}.lightbox{position:fixed;inset:0;z-index:10000;background:rgba(0,0,0,.88);display:grid;place-items:center;padding:30px}.lightbox img{max-width:94vw;max-height:90vh;object-fit:contain}.lightbox button{position:absolute;right:20px;top:10px;border:0;background:none;color:#fff;font-size:40px}.tag-page{max-width:900px;margin:90px auto;padding-bottom:100px}.tag-cloud{display:flex;flex-wrap:wrap;gap:10px;margin:30px 0}.tag-cloud a{border:1px solid var(--border);padding:8px 14px;border-radius:999px}.search-page input{width:100%;padding:16px;border:1px solid var(--border);border-radius:12px;background:var(--surface);font:inherit}.search-result{display:block;padding:22px 0;border-bottom:1px solid var(--border)}@media(max-width:700px){.related-grid{grid-template-columns:1fr}}`;
const libs=`<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.22/dist/katex.min.css"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/highlight.js@11.11.1/styles/github-dark.min.css">`;
const scripts=`<script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.22/dist/katex.min.js"></script><script defer src="https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.min.js"></script><script defer src="https://cdn.jsdelivr.net/npm/highlight.js@11.11.1/lib/common.min.js"></script><script defer src="../reading.js"></script><script defer src="../share.js"></script><script defer src="../images.js"></script><script>window.addEventListener('DOMContentLoaded',()=>{if(window.hljs)document.querySelectorAll('pre code').forEach(e=>hljs.highlightElement(e));if(window.mermaid)mermaid.initialize({startOnLoad:true,theme:document.body.classList.contains('dark')?'dark':'default'});if(window.katex)document.querySelectorAll('.math-block').forEach(e=>katex.render(e.textContent,e,{displayMode:true,throwOnError:false}));document.querySelectorAll('pre').forEach(p=>{const b=document.createElement('button');b.className='copy-code';b.textContent='复制';b.onclick=()=>navigator.clipboard?.writeText(p.querySelector('code')?.innerText||'').then(()=>b.textContent='已复制');p.appendChild(b)})});</script>`;
const shell=(title,desc,body,canonical,depth='../',extra='')=>`<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="${attr(desc)}"><meta property="og:title" content="${attr(title)}"><meta property="og:description" content="${attr(desc)}"><meta property="og:type" content="article"><link rel="canonical" href="${canonical}"><title>${attr(title)} · Darkmatter</title><link rel="alternate" type="application/rss+xml" title="Darkmatter RSS" href="${depth}feed.xml"><link rel="stylesheet" href="${depth}style.css">${libs}<style>${baseCss}${enhancedCss}.article{max-width:900px;margin:90px auto;padding-bottom:100px}.article h1{font-size:clamp(38px,6vw,64px);line-height:1.12;letter-spacing:-.05em}.article .lead{font-size:19px;color:var(--muted)}.article-layout{display:grid;grid-template-columns:minmax(0,1fr) 210px;gap:56px;margin-top:40px}.article-body{font-size:18px;line-height:1.9}.article-body h2{margin-top:48px}.article-body blockquote{border-left:3px solid var(--accent);padding:10px 20px;color:var(--muted);background:var(--accent-2)}.article-body pre{overflow:auto;padding:18px;border-radius:12px;background:#151515;color:#eee}.article-body code{background:var(--accent-2);padding:2px 6px;border-radius:5px}.toc{position:sticky;top:90px;align-self:start;font-size:14px}.toc a{display:block;padding:5px 0;color:var(--muted)}.post-nav{display:flex;justify-content:space-between;gap:20px;border-top:1px solid var(--border);margin-top:70px;padding-top:25px}.post-nav a{max-width:45%}@media(max-width:800px){.article-layout{display:block}.toc{position:static;margin-bottom:35px}.post-nav{display:block}.post-nav a{display:block;max-width:none;margin:12px 0}}</style></head><body><header class="site-header"><nav class="nav container"><a class="brand" href="${depth}"><span>DM</span> Darkmatter</a><div class="nav-links"><a href="${depth}#articles">文章</a><a href="${depth}archive.html">归档</a><a href="${depth}tags.html">标签</a><a href="${depth}search.html">搜索</a><a href="${depth}#about">关于</a><a href="https://github.com/Darkmatter131420">GitHub ↗</a></div></nav></header>${body}<footer class="footer container"><span>© ${new Date().getFullYear()} Darkmatter</span><span>Markdown · GitHub Pages</span></footer>${scripts}${extra}</body></html>`;
const published=posts.filter(p=>!p.draft);const cards=published.map((p,i)=>`<article class="post ${i===0?'featured':''}"><div class="post-meta"><span>${p.tags.map(esc).join(' · ')}</span><time>${p.date}</time></div><h3>${esc(p.title)}</h3><p>${esc(p.excerpt)}</p><a class="read-more" href="posts/${p.slug}.html">阅读全文 <span>→</span></a></article>`).join('');
let index=fs.readFileSync(path.join(root,'index.html'),'utf8').replace(/<div class="post-grid" id="postGrid">[\s\S]*?<\/div>\s*<p id="emptyState"/,`<div class="post-grid" id="postGrid">${cards}</div><p id="emptyState"`);index=index.replace('<a href="#articles">文章</a>','<a href="#articles">文章</a><a href="archive.html">归档</a><a href="tags.html">标签</a><a href="search.html">搜索</a>');fs.writeFileSync(path.join(siteDir,'index.html'),index);fs.copyFileSync(path.join(root,'style.css'),path.join(siteDir,'style.css'));['script.js','reading.js','share.js','images.js'].forEach(f=>fs.copyFileSync(path.join(root,f),path.join(siteDir,f)));
published.forEach((p,i)=>{const parsed=markdown(p.content),prev=published[i+1],next=published[i-1],related=published.filter(x=>x.slug!==p.slug&&x.tags.some(t=>p.tags.includes(t))).slice(0,2),toc=parsed.toc.length?`<aside class="toc"><strong>目录</strong>${parsed.toc.map(x=>`<a href="#${x.id}">${x.text}</a>`).join('')}</aside>`:'',rel=related.length?`<section class="related"><p class="eyebrow">KEEP READING</p><h2>相关文章</h2><div class="related-grid">${related.map(x=>`<a class="related-card" href="${x.slug}.html"><span>${x.tags.map(esc).join(' · ')}</span><h3>${esc(x.title)}</h3><p>${esc(x.excerpt)}</p></a>`).join('')}</div></section>`:'',body=`<main class="article container"><a class="read-more" href="../">← 返回首页</a><p class="eyebrow">${p.tags.map(esc).join(' · ')} · ${p.date} · ${readingTime(p.content)} 分钟阅读</p><h1>${esc(p.title)}</h1><p class="lead">${esc(p.excerpt)}</p><p><button class="button" data-share>分享</button></p><div class="article-layout"><div><div class="article-body">${parsed.html}</div>${rel}<nav class="post-nav">${prev?`<a href="${prev.slug}.html">← ${esc(prev.title)}</a>`:'<span>'}${next?`<a href="${next.slug}.html">${esc(next.title)} →</a>`:'<span>'}</nav></div>${toc}</div></main>`;fs.writeFileSync(path.join(siteDir,'posts',`${p.slug}.html`),shell(p.title,p.excerpt,body,`https://darkmatter131420.github.io/-Weblog/personal-blog/posts/${p.slug}.html`));});
const archiveGroups={};published.forEach(p=>(archiveGroups[p.date.slice(0,4)]??=[]).push(p));const archiveBody=Object.entries(archiveGroups).map(([y,items])=>`<section><p class="eyebrow">${y}</p>${items.map(p=>`<article class="post"><div class="post-meta"><span>${p.tags.join(' · ')}</span><time>${p.date}</time></div><h3><a href="posts/${p.slug}.html">${esc(p.title)}</a></h3><p>${esc(p.excerpt)}</p></article>`).join('')}</section>`).join('');fs.writeFileSync(path.join(siteDir,'archive.html'),shell('文章归档','按年份浏览 Darkmatter 的全部文章',`<main class="article container"><p class="eyebrow">ARCHIVE</p><h1>文章归档</h1>${archiveBody}</main>`,'https://darkmatter131420.github.io/-Weblog/personal-blog/archive.html'));
const tags={};published.forEach(p=>p.tags.forEach(t=>(tags[t]??=[]).push(p)));const tagBody=Object.entries(tags).sort().map(([t,items])=>`<section id="${slugify(t)}"><h2>${esc(t)} <small>${items.length}</small></h2>${items.map(p=>`<article class="post"><div class="post-meta"><time>${p.date}</time></div><h3><a href="posts/${p.slug}.html">${esc(p.title)}</a></h3><p>${esc(p.excerpt)}</p></article>`).join('')}</section>`).join('');fs.writeFileSync(path.join(siteDir,'tags.html'),shell('标签','按主题浏览 Darkmatter 的文章',`<main class="tag-page container"><p class="eyebrow">TAGS</p><h1>按主题阅读</h1><div class="tag-cloud">${Object.keys(tags).sort().map(t=>`<a href="#${slugify(t)}">${esc(t)} · ${tags[t].length}</a>`).join('')}</div>${tagBody}</main>`,'https://darkmatter131420.github.io/-Weblog/personal-blog/tags.html','../'));
const searchBody=`<main class="tag-page search-page container"><p class="eyebrow">SEARCH</p><h1>搜索文章</h1><input id="q" type="search" placeholder="输入关键词…" autofocus><div id="results" class="search-results"></div></main>`;const searchScript=`<script>const POSTS=${JSON.stringify(published.map(({content,...p})=>p))};const q=document.getElementById('q'),r=document.getElementById('results');const x=s=>String(s).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));function go(){const k=q.value.trim().toLowerCase();r.innerHTML=POSTS.filter(p=>!k||[p.title,p.excerpt,...p.tags].join(' ').toLowerCase().includes(k)).map(p=>'<a class="search-result" href="posts/'+encodeURIComponent(p.slug)+'.html"><small>'+x(p.date)+' · '+x(p.tags.join(' · '))+'</small><h3>'+x(p.title)+'</h3><p>'+x(p.excerpt)+'</p></a>').join('')||'<p>没有找到相关文章。</p>'}q.oninput=go;go();</script>`;fs.writeFileSync(path.join(siteDir,'search.html'),shell('搜索','搜索 Darkmatter 的全部文章',searchBody,'https://darkmatter131420.github.io/-Weblog/personal-blog/search.html','../',searchScript));
const publicMeta=published.map(({content,...p})=>({...p,readingTime:readingTime(content)}));fs.writeFileSync(path.join(siteDir,'posts.json'),JSON.stringify(publicMeta,null,2));const feed=`<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"><channel><title>Darkmatter · 个人博客</title><link>https://darkmatter131420.github.io/-Weblog/personal-blog/</link><description>Darkmatter 的个人博客</description>${published.map(p=>`<item><title>${esc(p.title)}</title><link>https://darkmatter131420.github.io/-Weblog/personal-blog/posts/${p.slug}.html</link><pubDate>${new Date(p.date).toUTCString()}</pubDate><description>${esc(p.excerpt)}</description></item>`).join('')}</channel></rss>`;fs.writeFileSync(path.join(siteDir,'feed.xml'),feed);fs.writeFileSync(path.join(siteDir,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>https://darkmatter131420.github.io/-Weblog/personal-blog/</loc></url><url><loc>https://darkmatter131420.github.io/-Weblog/personal-blog/archive.html</loc></url>${published.map(p=>`<url><loc>https://darkmatter131420.github.io/-Weblog/personal-blog/posts/${p.slug}.html</loc><lastmod>${p.date}</lastmod></url>`).join('')}</urlset>`);fs.writeFileSync(path.join(siteDir,'robots.txt'),'User-agent: *\nAllow: /\n\nSitemap: https://darkmatter131420.github.io/-Weblog/personal-blog/sitemap.xml\n');console.log(`Built ${published.length} published posts (${posts.length-published.length} drafts).`);
