const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
$('#year').textContent=new Date().getFullYear();
const toggle=$('#themeToggle'),saved=localStorage.getItem('blog-theme');if(saved==='dark')document.body.classList.add('dark');
function icon(){toggle.textContent=document.body.classList.contains('dark')?'☀':'☾'}icon();toggle.onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('blog-theme',document.body.classList.contains('dark')?'dark':'light');icon()};
let allPosts=[],activeTag='all';
fetch('./posts/index.json').then(r=>r.json()).then(posts=>{allPosts=posts.sort((a,b)=>b.date.localeCompare(a.date));render();renderArchive()}).catch(()=>$('#emptyState').hidden=false);
function render(){const q=$('#searchInput').value.trim().toLowerCase(),grid=$('#postGrid');let visible=0;grid.innerHTML=allPosts.map((p,i)=>{const ok=(activeTag==='all'||p.tags.includes(activeTag))&&(!q||`${p.title} ${p.excerpt} ${p.tags.join(' ')}`.toLowerCase().includes(q));if(ok)visible++;return ok?`<article class="post ${i===0?'featured':''}"><div class="post-meta"><span>${p.tags.join(' · ')}</span><time>${p.date}</time></div><h3>${esc(p.title)}</h3><p>${esc(p.excerpt)}</p><a class="read-more" href="./post.html?slug=${encodeURIComponent(p.slug)}">阅读全文 <span>→</span></a></article>`:''}).join('');$('#emptyState').hidden=visible!==0}
function renderArchive(){const groups={};allPosts.forEach(p=>{const y=p.date.slice(0,4);(groups[y]??=[]).push(p)});$('#archiveList').innerHTML=Object.entries(groups).map(([y,ps])=>`<div class="archive-year"><h3>${y}</h3><div>${ps.map(p=>`<a href="./post.html?slug=${encodeURIComponent(p.slug)}"><span>${esc(p.title)}</span><time>${p.date.slice(5)}</time></a>`).join('')}</div></div>`).join('')}
$$('.tag').forEach(b=>b.onclick=()=>{$$('.tag').forEach(x=>x.classList.remove('active'));b.classList.add('active');activeTag=b.dataset.tag;render()});$('#searchInput').oninput=render;
function esc(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
